language: android

android:
  components:
  - build-tools-20.0.0
  - android-19
  licenses:
  - 'android-sdk-license.*'

branches:
  only:
    - master

notifications:
  email: false

script: 'gradle build'

